services:
  client:
    image: zerotlt/rgszh-miniapp:prod
    depends_on:
      - api
    ports:
      - "80:80"
    restart: always

  api:
    image: zerotlt/rgszh-miniapp-api:prod
    ports:
      - "5000:5000"
    restart: always
    environment:
      - FLASK_ENV=production
      - PORT=5000

