services:
  server:
    image: zerotlt/rgszh-miniapp-api:latest
    ports:
      - "4000:4000"
    env_file:
      - .env
    networks:
      - rgszh-miniapp-network
    restart: always
    # Переопределяем entrypoint и command для обхода проблемы с docker-entrypoint.sh
    entrypoint: ["python"]
    command: ["server.py"]
    working_dir: /app
    depends_on:
      - redis

  frontend:
    image: zerotlt/rgszh-miniapp:latest
    restart: always
    ports:
      - "8080:80"
    networks:
      - rgszh-miniapp-network
    depends_on:
      - server

  proxy:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/ssl:ro
    depends_on:
      - server
      - frontend
    networks:
      - rgszh-miniapp-network

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - rgszh-miniapp-network

environment:
  - DB_HOST=172.17.0.1

networks:
  rgszh-miniapp-network:
    driver: bridge






