version: "3.8"

services:
  # 1) PostgreSQL — лёгкий образ, данные хранятся в томе pgdata
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER:     appuser
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB:       feedbackdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2) Ваш Flask‑сервер (API)
  server:
    image: zerotlt/rgszh-miniapp-api:prod
    ports:
      - "5000:5000"
    restart: always
    environment:
      - FLASK_ENV=production
      - PORT=5000
      # Подключаем SQLAlchemy к Postgres
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://appuser:secretpassword@postgres:5432/feedbackdb
      - SQLALCHEMY_TRACK_MODIFICATIONS=false
      # ... ваши другие переменные (SMTP и т.д.) ...
    depends_on:
      - postgres
    networks:
      default:
        aliases:
          - api

  # 3) Ваш React‑клиент
  client:
    image: zerotlt/rgszh-miniapp:prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/rgszh-miniapp.org/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/rgszh-miniapp.org/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    depends_on:
      - server

volumes:
  pgdata:



