version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: zerotlt/rgszh-miniapp:prod
    ports:
      - "80:80"       # ← вот эта строка обязательно должна быть
    restart: unless-stopped
