version: "3.8"

services:
  server:
    image: zerotlt/rgszh-miniapp-api:${TAG}
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      PORT: "5000"
      # здесь «postgres» — это имя вашего БД-контейнера в сети rgszh-net
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://postgres:secret@postgres:5432/postgres"
      SQLALCHEMY_TRACK_MODIFICATIONS: "false"
    networks:
      - rgszh-net

  client:
    image: zerotlt/rgszh-miniapp:${TAG}
    restart: always
    depends_on:
      - server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/rgszh-miniapp.org/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/rgszh-miniapp.org/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - rgszh-net

networks:
  rgszh-net:
    external: true




