version: "3.8"

services:
  # 1) PostgreSQL
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER:     appuser
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB:       feedbackdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "1111:5432"

  # 2) Flask-API
  server:
    image: zerotlt/rgszh-miniapp-api:prod
    restart: always
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV:                    production
      PORT:                         "5000"
      SQLALCHEMY_DATABASE_URI:      postgresql+psycopg2://appuser:secretpassword@postgres:5432/feedbackdb
      SQLALCHEMY_TRACK_MODIFICATIONS: "false"

  # 3) React-клиент с Nginx и SSL
  client:
    image: zerotlt/rgszh-miniapp:prod
    restart: always
    depends_on:
      - server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/rgszh-miniapp.org-0001/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/rgszh-miniapp.org-0001/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

# Объявляем том для постоянного хранения данных Postgres
volumes:
  pgdata:




