version: "3.8"

services:
  client:
    image: zerotlt/rgszh-miniapp:prod
    ports:
      - "80:80"
    restart: always

  server:
    image: zerotlt/rgszh-miniapp-api:prod
    ports:
      - "5000:5000"
    restart: always
    environment:
      - FLASK_ENV=production
      - PORT=5000
      # Добавьте здесь остальные переменные окружения при необходимости

