version: '3.8'
services:
  app:
    image: zerotlt/rgszh-miniapp:prod
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    image: zerotlt/rgszh-miniapp-api:prod
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    # если твой API слушает порт 5000 внутри контейнера,
    # ему не обязательно пробрасывать наружу

networks:
  default:
    driver: bridge

