version: '3.9'
services:

  server:
    image: zerotlt/rgszh-miniapp-api:latest  # ← ИСПРАВЛЕНО: :prod → :latest
    ports:
      - "4000:4000"
    env_file:
      - .env
    networks:
      - rgszh-miniapp-network
    restart: always

  frontend:
    image: zerotlt/rgszh-miniapp:latest      # ← ИСПРАВЛЕНО: :prod → :latest
    restart: always
    ports:
      - "8080:80"
    networks:
      - rgszh-miniapp-network
    depends_on:
      - server

  proxy:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/ssl:ro
    depends_on:
      - server
      - frontend
    networks:
      - rgszh-miniapp-network

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - rgszh-miniapp-network

networks:
  rgszh-miniapp-network:
    driver: bridge






