version: '3.8'
services:
  app:
    image: zerotlt/rgszh-miniapp:prod
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    image: zerotlt/rgszh-miniapp-api:prod
    # если у вас есть свой Dockerfile в папке ./api, то вместо image укажите:
    # build:
    #   context: ./api
    #   dockerfile: Dockerfile
    # и, при необходимости, прокиньте порты:
    # ports:
    #   - "5000:5000"
    environment:
      - FLASK_ENV=production
      # все ваши переменные окружения
