version: "3.8"

services:
  server:
    image: zerotlt/rgszh-miniapp-api:prod
    restart: always
    # Вот это подключит контейнер server к существующей сети rgszh-miniapp_default:
    network_mode: "rgszh-miniapp_default"
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: "production"
      PORT:      "5000"
      # обращаемся к Postgres по его контейнерному имени и порту 5432
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://postgres:secret@postgres:5432/postgres"
      SQLALCHEMY_TRACK_MODIFICATIONS: "false"

  client:
    image: zerotlt/rgszh-miniapp:prod
    restart: always
    network_mode: "rgszh-miniapp_default"
    depends_on:
      - server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/rgszh-miniapp.org/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/rgszh-miniapp.org/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - ./rgszh-miniapp/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro




