version: '3.8'
services:
  api:
    image: zerotlt/rgszh-miniapp-api:prod
    environment:
      - FLASK_ENV=production
    expose:
      - "5000"

  app:
    image: zerotlt/rgszh-miniapp:prod
    depends_on:
      - api
    ports:
      - "80:80"

