version: '3.9'
services:

  server:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    networks:
      - rgszh-miniapp-network

  # (ваш API-сервис)

  frontend:
    # вместо image: nginx:... — собираем наш multi-stage Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    image: miniapp-frontend:latest
    restart: always
    ports:
      - "8080:80"           # проксируем порт nginx внутри контейнера
    networks:
      - rgszh-miniapp-network
    depends_on:
      - server

  proxy:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl:ro
    depends_on:
      - server
      - frontend
    networks:
      - rgszh-miniapp-network

networks:
  rgszh-miniapp-network:
    driver: bridge






